In [4]:
import pandas as pd

data ={'Candidato':['A','B','C','D','E','F','G','H','A','B','A','B','C','D','E','F','A','F','A','B','C','D','E','F', 'A','F'],
            'Partido':['PAP','PCG','PLT','PSS','PPP', 'PXY', 'PSK','PVC','PAP','PCG','PSK','PCG','PLT','PSS', 'PPP','PXY','PSK','PXY','PSK','PCG','PLT','PVC','PPP','PXY','PSK','PXY'],
'Votos':[28, 12, 13, 10, 10, 9, 9, 9, 67, 33, 28, 9, 19, 13,11, 20, 42, 58, 25, 12, 21, 9, 10, 23, 51, 49],
'Ano':[2018,2018,2018,2018,2018,2018,2018,2018,2018,2018,2014,2014,2014,2014,2014,2014,2014, 2014,2010,2010,2010,2010,2010,2010,2010,2010],
       'Turno':[1,1,1,1,1,1,1,1,2,2,1,1,1,1,1,1,2,2,1,1,1,1,1,1,2,2]}

df = pd.DataFrame(data)

df

   Candidato Partido  Votos   Ano  Turno
0          A     PAP     28  2018      1
1          B     PCG     12  2018      1
2          C     PLT     13  2018      1
3          D     PSS     10  2018      1
4          E     PPP     10  2018      1
5          F     PXY      9  2018      1
6          G     PSK      9  2018      1
7          H     PVC      9  2018      1
8          A     PAP     67  2018      2
9          B     PCG     33  2018      2
10         A     PSK     28  2014      1
11         B     PCG      9  2014      1
12         C     PLT     19  2014      1
13         D     PSS     13  2014      1
14         E     PPP     11  2014      1
15         F     PXY     20  2014      1
16         A     PSK     42  2014      2
17         F     PXY     58  2014      2
18         A     PSK     25  2010      1
19         B     PCG     12  2010      1
20         C     PLT     21  2010      1
21         D     PVC      9  2010      1
22         E     PPP     10  2010      1
23         F     PXY     23  2010      1
24         A     PSK     51  2010      2
25         F     PXY     49  2010      2

In [7]:
df.loc[(df["Votos"]>10) & (df["Ano"]==2018) & (df["Turno"]==1)]

  Candidato Partido  Votos   Ano  Turno
0         A     PAP     28  2018      1
1         B     PCG     12  2018      1
2         C     PLT     13  2018      1

In [10]:
df["Votos"]> 10

0      True
1      True
2      True
3     False
4     False
5     False
6     False
7     False
8      True
9      True
10     True
11    False
12     True
13     True
14     True
15     True
16     True
17     True
18     True
19     True
20     True
21    False
22    False
23     True
24     True
25     True
Name: Votos, dtype: bool

In [11]:
df.query("Votos > 10 & Ano == 2018 & Turno == 1")

  Candidato Partido  Votos   Ano  Turno
0         A     PAP     28  2018      1
1         B     PCG     12  2018      1
2         C     PLT     13  2018      1

O método describe é uma ferramenta interessante para obter informações estatísticas do dataframe que estamos analisando. Em particular, quando combinado com os métodos loc, iloc ou query, esse método torna-se bastante poderoso na análise de dados massivos. Considerando o dataframe mostrado anteriormente, use a combinação de métodos loc/iloc/query + describe() para responder a seguinte pergunta: qual a média (mean) e desvio padrão (std) de votos recebidos pelo partido PSK no primeiro turno das três eleições mostradas?

In [21]:
# Filtrando o dataframe para o partido PSK no primeiro turno
psk_first_turn = df.query("Partido == 'PSK' & Turno == 1")

# Calculando a média e o desvio padrão dos votos recebidos pelo partido PSK no primeiro turno
statistics = psk_first_turn.describe().loc[['mean', 'std'], 'Votos']

print("Média de votos recebidos pelo partido PSK no primeiro turno:")
print(statistics['mean'])

print("\nDesvio padrão de votos recebidos pelo partido PSK no primeiro turno:")
print(statistics['std'])

Média de votos recebidos pelo partido PSK no primeiro turno:
20.666666666666668

Desvio padrão de votos recebidos pelo partido PSK no primeiro turno:
10.214368964029708